name: Crypto Indicators

on:
  workflow_dispatch:

  schedule:
    - cron: '1 * * * *'   # Daily 09:05 AM IST

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify TA Library
        run: |
          python -c "import pandas_ta_classic as ta; print('TA_CLASSIC_OK')"

      - name: Run OHLCV
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python OHLCV.py

      - name: Run Indicators
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python "indicator_pipeline_v2 (2).py"
